---
title: "BU425_project_v1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import libraries
library(ggplot2)
library(dplyr)
```

## R Markdown

# Telecom Churn Data

Business Problem:
Analytic Problem:
Goal:

## Load and Describe Data

The data was found off of Kaggle (https://www.kaggle.com/datasets/yeanzc/telco-customer-churn-ibm-dataset/data) for a hypothetical telecom company with data from IBM 

```{r}
#import data
initial_data<- read.csv("Telco_customer_churn.csv")
head(initial_data)
```
```{r}
# Look at the makeup of the data
str(initial_data)
# 7043 rows and 33 columns 
# target variable: Churn Label / Churn Value
```


```{r}
# count the target variable
initial_data %>%
  group_by(Churn.Value) %>%
  summarise(count = n(), 
            percentage = paste0(round(count/nrow(initial_data)*100,0),"%"),
            .groups="drop")
```

## Dealing with Missing Values

```{r}
# check for missing values
colSums(is.na(initial_data))
#can see that total charges has 11 observations missing
```

```{r}
# shows the rows in which total charges is NA
missing_val<- initial_data[is.na(initial_data$Total.Charges),]
missing_val
# these missing values are when churn = 0 so they are staying with the company
```

```{r}
# dropping the NA values, would not contribute much in our findings as we have about 73% of the data that is not churn (churn = 0)
data<- na.omit(initial_data)
colSums(is.na(data))
```

## Exploratory Data Analysis

```{r}
# changing the value of the variables to do some analysis on
# data$Churn.Value<- as.factor(data$Churn.Value)
# data$Gender[data$Gender=="Male"]<- 0
# data$Gender[data$Gender=="Female"]<- 1
# str(data)
```


```{r}
# distribution of target variable -> maybe do a pie chart instead?
data %>% 
  ggplot(aes(x = Churn.Label, fill = Churn.Label))+
  geom_bar(aes(y = after_stat(count)/sum(after_stat(count))))+
  ylab("Proportion")+
  xlab("Churn Value")+
  ggtitle("Distribution of Churn Rate")+
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")

```
```{r}
data %>% 
  group_by(Gender, Churn.Label) %>% 
  summarise(count = n(),
            .groups = "drop") %>% 
  mutate(prop = paste0(round(count/sum(count)*100, 0), '%')) %>% 
  ggplot(aes(x = Gender, y = count, fill = Churn.Label)) +
  geom_col(position = "stack") +
 # geom_text(aes(label = prop), vjust = 1, size = 3) +
  ggtitle("Counts of Churn Rate by Gender")+
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")

# There are similar numbers of customers by gender, with each having similar proportions that leave versus remaining with the company
```

```{r}
# distribution by senior for churn rate
data %>% 
  group_by(Senior.Citizen, Churn.Label) %>% 
  summarise(count = n(),
            .groups = "drop") %>% 
  mutate(prop = paste0(round(count/sum(count)*100, 0), '%')) %>% 
  ggplot(aes(x = Senior.Citizen, y = count, fill = Churn.Label)) +
  geom_col(position = "stack") +
 # geom_text(aes(label = prop), vjust = 1, size = 3) +
  ggtitle("Counts of Churn Rate by Senior Citizen category")+
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")

#The majority of customers are not senior citizens, but those that are have a higher likelihood to leave
```


```{r}
data %>% 
  group_by(Contract, Churn.Label) %>% 
  summarise(count = n(),
            .groups = "drop") %>% 
  mutate(prop = paste0(round(count/sum(count)*100, 0), '%')) %>% 
  ggplot(aes(x = reorder(Contract, -count), y = count, fill = Churn.Label)) +
  geom_col(position = "stack") +
  #geom_text(aes(label = prop), vjust = 1, size = 3) +
  ggtitle("Counts of Churn Rate by Type of Contract")+
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")+
  xlab("Type of Contract")

# this distribution shows that there are more people leaving the company with a contract that is month-to month vs those that are fixed for one or two years. This makes sense because they are paying buy however many months they want the service for.
```
```{r}
data %>% 
  group_by(Internet.Service, Churn.Label) %>% 
  summarise(count = n(),
            .groups = "drop") %>% 
  mutate(prop = paste0(round(count/sum(count)*100, 0), '%')) %>% 
  ggplot(aes(x = reorder(Internet.Service, -count), y = count, fill = Churn.Label)) +
  geom_col(position = "stack") +
 # geom_text(aes(label = prop), vjust = 1, size = 3) +
  ggtitle("Counts of Churn Rate by Internet Service") +
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")+
  xlab("Type of Internet Services")

#Most customers have Fibre Optic internet services, but this category also has the largest proportion of customers that leave the company
```


```{r}
data %>% 
  group_by(Payment.Method, Churn.Label) %>% 
  summarise(count = n(),
            .groups = "drop") %>% 
  mutate(prop = paste0(round(count/sum(count)*100, 0), '%')) %>% 
  ggplot(aes(x = reorder(Payment.Method, count), y = count, fill = Churn.Label)) +
  geom_col(position = "stack") +
 # geom_text(aes(label = prop), vjust = 1, size = 3) +
  ggtitle("Counts of Churn Rate by Payment Method")+
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")+
  xlab("Payment Method")+
  coord_flip()


# Based on these results the majority of customers choose to pay by electronic cheque. However, this also leads to higher likelihood of customer loss.
```

```{r}
# plots for continuous variables

data %>%
  ggplot(aes(x = Tenure.Months, fill = Churn.Label))+
  geom_histogram(bins = 30)+
  ggtitle("Distribution of Tenure by Churn Label")+
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")+
  xlab("Tenure Months")

# Customers who have been with the company for a shorter period of time are more likely to leave, with a median of 10 months.

```
```{r}
data %>%
  ggplot(aes(x = Total.Charges, y = Churn.Label, fill = Churn.Label))+
  geom_boxplot()+
  ggtitle("Distribution of Total Charges by Churn Label")+
  theme(plot.title = element_text(hjust = 0.5))+ # centers the title
  scale_fill_brewer(palette = "Set2")

# Although there are more outliers, it appears that customers who left the company had a lower median total charge than those who remained with the company. This may indicate that cost alone may not be the motivating factor that causes customers to leave.

```

```{r}
# reason for leaving

data %>% 
  filter(Churn.Value == 1) %>% 
  group_by(Churn.Reason) %>% 
  summarise(count = n(),
           .groups = 'drop') %>% 
  mutate(perc =paste0(round(count / sum(count)*100, 0),'%')) %>% 
  arrange(desc(count))

# About 10% of the customers who left, did so due to price or charges
```


After doing some exploratory data analysis we realized some columns were not providing us additional information. 

```{r}
# need to drop specific columns 
# (do we need both churn value and churn label?), lat long (we have the latitude and longitude separated) , state (all California), Country (all in the United States)
newdata<- select(data, -c(Lat.Long, State, Country, Churn.Value, Count, CLTV, Churn.Score))
head(newdata)

# data that won't be available for why they left (can't use for prediction) 
```

```{r}
# rename the columns
newdata %>%
  rename(ZipCode = Zip.Code,
         SeniorCitizen = Senior.Citizen,
         TenureMonths = Tenure.Months,
         PhoneService = Phone.Service,
         MultipleLines = Multiple.Lines,
         InternetService = Internet.Service,
         OnlineSecurity = Online.Security,
         OnlineBackup = Online.Backup,
         DeviceProtection = Device.Protection,
         TechSupport = Tech.Support,
         StreamingTV = Streaming.TV,
         StreamingMovies = Streaming.Movies,
         PaperlessBilling = Paperless.Billing,
         PaymentMethod = Payment.Method,
         MonthlyCharges = Monthly.Charges,
         TotalCharges = Total.Charges,
         ChurnLabel = Churn.Label,
         ChurnReason = Churn.Reason)

```

